# fly.toml app configuration file generated for discord-searcher on 2026-04-07T13:09:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-searcher'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[processes]
  worker = 'python bot.py'

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
